apiVersion: v1
kind: Service
metadata:
  labels:
    app: openmrs
  name: openmrs
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: openmrs